### ISSUE TITLE
"scheduled" keyword not working as advertised

### ISSUE THREAD

**Issue by PiQuer** [taskjuggler/TaskJuggler#171]
According to the documentation, for a task with the  `scheduled` keyword the start and end date will be derived from the first and last booking in case those dates are not supplied.

However for this project:

    project pr "Project" 2015-05-28 +1w {
      scenario plan "Plan"
      trackingscenario plan
      now 2015-05-30
    }

    resource r "Resource" {}

    task task1 "Task 1" {
      scheduled
    }

    supplement resource r {
      booking task1 2015-05-29-09:00 + 1h
    }

I get this error with taskjuggler version 3.5.0: 

    Error: Task task1 is marked as scheduled but does not have a fixed start and end date.

**Comment by scrapper** [comment]
This issue was caused by an overeager check in the parser. Since there is a later, more sophisticated check for these types of issues in the scheduler, I've just removed the parser check.

The issue has been fixed now. Please checkout the latest version from github. Thanks for reporting this!

**Comment by PiQuer** [comment]
Thanks for fixing this so quickly!

**Comment by PiQuer** [comment]
@scrapper The error still is triggered if an effort value is given additionally:

    project pr "Project" 2015-05-28 +1w {
      scenario plan "Plan"
      trackingscenario plan
      now 2015-05-30
    }

    resource r "Resource" {}

    task task1 "Task 1" {
      scheduled
      effort 1h
    }

    supplement resource r {
      booking task1 2015-05-29-09:00 + 1h
    }

Maybe it is by design... but it might be helpful to mention this in the documentation, that you have to remove the effort assignment in the task if you want to mark it "scheduled".
